// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA483NJ9UydVobyXCBacJFSXioj2Z9BUQI',
    appId: '1:999481722155:web:7435f224b4c3d0cd8b316e',
    messagingSenderId: '999481722155',
    projectId: 'swin-55203',
    authDomain: 'swin-55203.firebaseapp.com',
    storageBucket: 'swin-55203.firebasestorage.app',
    measurementId: 'G-JT2X60P7MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7rGOSlgz28nLs_SiFnCTcGprlOEBUph8',
    appId: '1:999481722155:android:add031acc589c47a8b316e',
    messagingSenderId: '999481722155',
    projectId: 'swin-55203',
    storageBucket: 'swin-55203.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyJEHzG82jJmt0fn_y1_GFIFFLpaQ4w8Q',
    appId: '1:999481722155:ios:f8e6182e37d3ad0f8b316e',
    messagingSenderId: '999481722155',
    projectId: 'swin-55203',
    storageBucket: 'swin-55203.firebasestorage.app',
    iosBundleId: 'com.vuha14.swin',
  );
}
